### ISSUE TITLE
Incorrect genesis file?

### ISSUE THREAD

**Issue by datacryp** [shibaswaparmy/launch#15]
So Im trying to setup my shibarium node, and I found out that there seems to be an issue with the genesis file at https://github.com/shibaswaparmy/launch/blob/mainnet/dev/without-sentry/heimdall/config/genesis.json.

At height 5 Im getting the following error:

```
heimdall-shib  | I[2023-08-17|16:29:07.663] Executed block                               module=state height=2 validTxs=0 invalidTxs=0                                                             heimdall-shib  | I[2023-08-17|16:29:07.664] Committed state                              module=state height=2 txs=0 appHash=C7D62B51AE9DADB0AE97CC5BA8E191E0ED719FE72CCD63E3AAC0B6927A85517B
heimdall-shib  | I[2023-08-17|16:29:07.674] Executed block                               module=state height=3 validTxs=1 invalidTxs=0                                                             heimdall-shib  | I[2023-08-17|16:29:07.675] Committed state                              module=state height=3 txs=1 appHash=6774CECCD8C6642405287529ABE81AAD45E3AE043F40FC0D50C24F176EBA23D1
heimdall-shib  | I[2023-08-17|16:29:07.679] Executed block                               module=state height=4 validTxs=0 invalidTxs=0                                                             heimdall-shib  | I[2023-08-17|16:29:07.679] Committed state                              module=state height=4 txs=0 appHash=6774CECCD8C6642405287529ABE81AAD45E3AE043F40FC0D50C24F176EBA23D1
heimdall-shib  | I[2023-08-17|16:29:07.753] Executed block                               module=state height=5 validTxs=0 invalidTxs=0                                                             heimdall-shib  | I[2023-08-17|16:29:07.754] Committed state                              module=state height=5 txs=0 appHash=3FC3365C75BD9D07477C6D16D4EA43782DEBFB9A18740941BF252F84863052F1
heimdall-shib  | panic: Failed to process committed block (6:B8404749077750E3F27DFC9AF64AE5D6CCE932DA218DC3A03F41BDF2CA1AA129): Wrong Block.Header.AppHash.  Expected 3FC3365C75BD9D07477C6D16D4EA43782DEBFB9A18740941BF252F84863052F1, got 01433B87975EB6AC5D4EEABAFF20F4E9F92E3789168B159B834DEA3F72CB3824                                                                                    
heimdall-shib  |                                                                                                                                                                                   heimdall-shib  | goroutine 162 [running]:                                                                                                                                                          
heimdall-shib  | github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00017d500)                                                                                     heimdall-shib  |        /go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/blockchain/v0/reactor.go:344 +0x10a5                                       
heimdall-shib  | created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart                                                                                            heimdall-shib  |        /go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/blockchain/v0/reactor.go:118 +0x7a                                         
heimdall-shib exited with code 0                       
```

My guess is that there is an issue with the genesis file, since my setup is the same as for the testnet and that was working perfectly fine.

**Comment by datacryp** [comment]
My heimdalld version was outdated that was why the node was panicking
