### ISSUE TITLE
Persistent Peers missing port number

### ISSUE THREAD

**Issue by jjordan-quantum** [shibaswaparmy/launch#16]
Looks like port#'s missing in persistent peers here: 
https://github.com/shibaswaparmy/launch/blob/07f1295c853ba6a9ee03e4a00cedf25296ca6a65/dev/without-sentry/heimdall/heimdall-seeds.txt

Getting the following issue:

```
I[2023-08-17|19:47:59.873] starting ABCI with Tendermint                module=main 

E[2023-08-17|19:47:59.923] Error in peer's address                      module=p2p err="invalid address (75.101.231.169): address 75.101.231.169: missing port in address"

E[2023-08-17|19:47:59.923] Error in peer's address                      module=p2p err="invalid address (18.138.189.118): address 18.138.189.118: missing port in address"

E[2023-08-17|19:47:59.923] Error in peer's address                      module=p2p err="invalid address (99.79.90.7): address 99.79.90.7: missing port in address"

ERROR: could not add peers from persistent_peers field: invalid address (75.101.231.169): address 75.101.231.169: missing port in address

```

The first peer in the list was port 26656 - can we assume they should all be the same port?

**Comment by jjordan-quantum** [comment]
Also, should we have 30303 and 26656 open to all incoming / outgoing traffic?

**Comment by jjordan-quantum** [comment]
Updated all peers to use 26656 adn now getting this mesage:

```
E[2023-08-17|20:07:18.161] dialing failed (attempts: 7): dial tcp 18.138.189.118:26656: i/o timeout module=pex addr=61842ce9068819d9dce6fb6e4a66594f2a7dd7a3@18.138.189.118:26656
E[2023-08-17|20:07:18.161] dialing failed (attempts: 7): dial tcp 50.16.175.79:26656: i/o timeout module=pex addr=1bfc293e39363c7a26b75d14c3e8ab9cb23c19ae@50.16.175.79:26656
E[2023-08-17|20:07:18.161] dialing failed (attempts: 7): dial tcp 99.79.90.7:26656: i/o timeout module=pex addr=73d941179f2d3d9f5cd96af814b7d3122d61d1ee@99.79.90.7:26656
E[2023-08-17|20:07:48.161] dialing failed (attempts: 7): dial tcp 52.6.79.52:26656: i/o timeout module=pex addr=06e69bc898cd3f9c1a3b430785d8e1213f61bd09@52.6.79.52:26656
E[2023-08-17|20:07:48.161] dialing failed (attempts: 7): dial tcp 75.101.231.169:26656: i/o timeout module=pex addr=800317cf1d2907781b4fc452b55b578efd5a8c49@75.101.231.169:26656
```

**Comment by kaber2** [comment]
@jjordan-quantum  Did you manage to establish some connections to heimdall peers? After waiting for 12 hours, I still only get connections errors.

**Comment by pedrobonfim** [comment]
@jjordan-quantum @kaber2 

Did you manage to solve it? The seeds provided at launch repo are not working, and other seeds it discovers also fail to connect. I'm getting these errors here:

1: p2p err="incompatible: Peer is on a different network. Got heimdall-137, expected heimdall-109"
2: p2p err="dial tcp 44.xx.xx.71:26656: i/o timeout"

Because of this, when I check the status, I'm still at block 0.

**Comment by kaber2** [comment]
I did. The provided peers apparently regenerated their node key. Heimdall is strict about connecting to given peers, if the node key does not match, it won't connect.

persistent_peers = "65ff7ef5ec8ac20e6c8e6bec4b9f58d71289cbb4@185.229.191.148:26656,65ff7ef5ec8ac20e6c8e
6bec4b9f58d71289cbb4@89.187.177.158:26656,65ff7ef5ec8ac20e6c8e6bec4b9f58d71289cbb4@89.187.162.167:26656
,65ff7ef5ec8ac20e6c8e6bec4b9f58d71289cbb4@195.181.166.167:26656,65ff7ef5ec8ac20e6c8e6bec4b9f58d71289cbb
4@212.102.60.119:26656,65ff7ef5ec8ac20e6c8e6bec4b9f58d71289cbb4@89.187.161.243:26656"

I changed one of them, I believe it was the last one, and synchronization proceeded. I'm now at height=246179 and it appears to be fully synced up.

However bor still doesn't proceed further than block 249152, at which point it throws a consensus error:

Error: invalid merkle root (remote: 0782a87e20b1d259e14e84ef63f7d67b72161dbc290f96153c1d30cbe186861e local: 7516c27d5db616f365bb8794fa5f54e1e6428da66fb1e63f8f9dc56016b9c917)

That's as far as I got so far.

**Comment by poptye** [comment]
> I did. The provided peers apparently regenerated their node key. Heimdall is strict about connecting to given peers, if the node key does not match, it won't connect.
> 
> persistent_peers = "65ff7ef5ec8ac20e6c8e6bec4b9f58d71289cbb4@185.229.191.148:26656,65ff7ef5ec8ac20e6c8e 6bec4b9f58d71289cbb4@89.187.177.158:26656,65ff7ef5ec8ac20e6c8e6bec4b9f58d71289cbb4@89.187.162.167:26656 ,65ff7ef5ec8ac20e6c8e6bec4b9f58d71289cbb4@195.181.166.167:26656,65ff7ef5ec8ac20e6c8e6bec4b9f58d71289cbb 4@212.102.60.119:26656,65ff7ef5ec8ac20e6c8e6bec4b9f58d71289cbb4@89.187.161.243:26656"
> 
> I changed one of them, I believe it was the last one, and synchronization proceeded. I'm now at height=246179 and it appears to be fully synced up.
> 
> However bor still doesn't proceed further than block 249152, at which point it throws a consensus error:
> 
> Error: invalid merkle root (remote: 0782a87e20b1d259e14e84ef63f7d67b72161dbc290f96153c1d30cbe186861e local: 7516c27d5db616f365bb8794fa5f54e1e6428da66fb1e63f8f9dc56016b9c917)
> 
> That's as far as I got so far.



don't seem to be working, any new peers ?

**Comment by jjordan-quantum** [comment]
Can the Shib team please provide the genesis files and seeds/persistent peers for each client to connect to mainnet?
Thanks

**Comment by navdeepgarg1** [comment]
Give me some day for solve your issue

**Comment by jjordan-quantum** [comment]
@navdeepgarg1 if  you or anyone you work with is currently running a validator on mainnet, or has access to the genesis info / seeds / peers, plz update the repo.  Maybe Shib is not yet ready to allow RPC access to the network for non-validators?

**Comment by navdeepgarg1** [comment]
@jjordan-quantum team is working some other issue I will update everything very high traffic

**Comment by jjordan-quantum** [comment]
I see. Priorities I guess. Thanks for the update!

**Comment by navdeepgarg1** [comment]
My mail is navdeep@shib.io

**Comment by pedrobonfim** [comment]
@navdeepgarg1 
Will you update the repositories with an updated tutorial on how to set up only a full node, without the validator?

**Comment by navdeepgarg1** [comment]
next few days what ever you need

**Comment by jjordan-quantum** [comment]
How are things looking @navdeepgarg1?

**Comment by pedrobonfim** [comment]
@jjordan-quantum 
did you manage to sync your node? here nothing yet.

**Comment by jjordan-quantum** [comment]
> @jjordan-quantum did you manage to sync your node? here nothing yet.

No.  Waiting on the correct list of persistent peers and seeds

**Comment by jjordan-quantum** [comment]
I've updated the genesis file and seeds after installing with ansible (installed sentry node, as an option for RPC was not available, and it's not going to be validating blocks - so I assumed that was the right choice).  Getting this error when I start the heimdall:

```
Sep 09 01:39:19 ip-172-31-86-227 systemd[1]: Started heimdalld.
Sep 09 01:39:19 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:19.535] starting ABCI with Tendermint                module=main
Sep 09 01:39:19 ip-172-31-86-227 heimdalld[3863294]: E[2023-09-09|01:39:19.608] Error dialing seed                           module=p2p err="auth failure: conn.ID (a6fc97b91c180ab5f1806ebd16de0a3943b7d196) dialed ID (67966d02dd5dc1da6cfd7ee1b58afcbc1af89df4) mismatch" seed=67966d02dd5dc1da6cfd7ee1b58afcbc1af89df4@75.101.231.169:26656
Sep 09 01:39:19 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:19.932] Executed block                               module=state height=1 validTxs=0 invalidTxs=0
Sep 09 01:39:19 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:19.939] Committed state                              module=state height=1 txs=0 appHash=C7D62B51AE9DADB0AE97CC5BA8E191E0ED719FE72CCD63E3AAC0B6927A85517B
Sep 09 01:39:19 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:19.957] Executed block                               module=state height=2 validTxs=0 invalidTxs=0
Sep 09 01:39:19 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:19.962] Committed state                              module=state height=2 txs=0 appHash=C7D62B51AE9DADB0AE97CC5BA8E191E0ED719FE72CCD63E3AAC0B6927A85517B
Sep 09 01:39:19 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:19.979] Executed block                               module=state height=3 validTxs=1 invalidTxs=0
Sep 09 01:39:19 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:19.983] Committed state                              module=state height=3 txs=1 appHash=6774CECCD8C6642405287529ABE81AAD45E3AE043F40FC0D50C24F176EBA23D1
Sep 09 01:39:19 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:19.996] Executed block                               module=state height=4 validTxs=0 invalidTxs=0
Sep 09 01:39:19 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:19.998] Committed state                              module=state height=4 txs=0 appHash=6774CECCD8C6642405287529ABE81AAD45E3AE043F40FC0D50C24F176EBA23D1
Sep 09 01:39:20 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:20.068] Executed block                               module=state height=5 validTxs=0 invalidTxs=0
Sep 09 01:39:20 ip-172-31-86-227 heimdalld[3863294]: I[2023-09-09|01:39:20.071] Committed state                              module=state height=5 txs=0 appHash=3FC3365C75BD9D07477C6D16D4EA43782DEBFB9A18740941BF252F84863052F1
Sep 09 01:39:20 ip-172-31-86-227 heimdalld[3863294]: panic: Failed to process committed block (6:B8404749077750E3F27DFC9AF64AE5D6CCE932DA218DC3A03F41BDF2CA1AA129): Wrong Block.Header.AppHash.  Expected 3FC3365C75BD9D07477C6D16D4EA43782DEBFB9A18740941BF252F84863052F1, got 01433B87975EB6AC5D4EEABAFF20F4E9F92E3789168B159B834DEA3F72CB3824
Sep 09 01:39:20 ip-172-31-86-227 heimdalld[3863294]: goroutine 102 [running]:
Sep 09 01:39:20 ip-172-31-86-227 heimdalld[3863294]: github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000468e00)
Sep 09 01:39:20 ip-172-31-86-227 heimdalld[3863294]:         /home/ubuntu/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/blockchain/v0/reactor.go:344 +0x10c5
Sep 09 01:39:20 ip-172-31-86-227 heimdalld[3863294]: created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
Sep 09 01:39:20 ip-172-31-86-227 heimdalld[3863294]:         /home/ubuntu/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/blockchain/v0/reactor.go:118 +0x7a
Sep 09 01:39:20 ip-172-31-86-227 systemd[1]: heimdalld.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
